### ISSUE TITLE
Better documentation of containerClasses

### ISSUE THREAD

**Issue by andorfermichael** [acidjazz/tv-toast#13]
I failed on replacing the containerClasses with my own.

I tried to replace them as described in the readme, but it seems that the class is just added and not replacing the existing ones. 

Furthermore, I could not add more than one class, because adding more classes resulted in "class1, class2" in the dom instead of "class1 class2".

Could you provide an example of how to add multiple classes?

Thank you.

**Comment by acidjazz** [comment]
I have re-structured the `containerClasses` property to accept an array now for adding multiple classes, grab the latest version and try it again @andorfermichael . try `['class1', 'class2']` (readme has been updated).

Please close this if that works!

**Comment by andorfermichael** [comment]
> I have re-structured the `containerClasses` property to accept an array now for adding multiple classes, grab the latest version and try it again @andorfermichael . try `['class1', 'class2']` (readme has been updated).
> 
> Please close this if that works!

Thank you for the fast response. I will have a look asap.

**Comment by andorfermichael** [comment]
@acidjazz the classes are appended correctly now. Thank you again for the quick reaction.
