### ISSUE TITLE
Toast appears in middle of viewport on small screens

### ISSUE THREAD

**Issue by dosstx** [acidjazz/tv-toast#17]
Have a pretty basic NUXT installation and tailwind module. Out of the box, the toast appears in the middle of the viewport on small screens . Is this intended? If so, how would I fix so it stays at the top? Thanks.

**Comment by dloused** [comment]
check this [topic](https://github.com/acidjazz/tv-toast/issues/16#issue-815448698)

For now you can override by adding in your css styles for eg. 

```
@media screen and (max-width: 767px) {
    div#toasts {
        justify-content: flex-end;
    }
}
```
This will position the toast at the top

**Comment by acidjazz** [comment]
@dosstx Yes, this is intended and designed via tailwind, thanks @dloused
