### ISSUE TITLE
Cannot read property 'show' of undefined   

### ISSUE THREAD

**Issue by productfrontenddeveloper** [acidjazz/tv-toast#18]
ssr: true, yarn build and yarn start problem

yarn dev some problem

![Screen Shot 2021-03-01 at 22 22 00](https://user-images.githubusercontent.com/38668796/109547551-8bb1a100-7adc-11eb-8678-29f0a91ba13f.png)
![Screen Shot 2021-03-01 at 22 22 07](https://user-images.githubusercontent.com/38668796/109547564-8f452800-7adc-11eb-8417-7f972c68e62b.png)

**Comment by acidjazz** [comment]
I think I need to see more of the code, the plugin isn't really made to render via SSR since its programmatic, maybe check for process.client? did you try running this in the browser?

**Comment by productfrontenddeveloper** [comment]
<img width="1402" alt="Screen Shot 2021-03-02 at 06 33 09" src="https://user-images.githubusercontent.com/38668796/109592936-2b911e00-7b21-11eb-9f3b-5b3462481ad5.png">

**Comment by productfrontenddeveloper** [comment]
used onMounted in code fixed. 
```onMounted(() => {
      context.app.$toast.show({
        type: 'danger',
        title: 'Error',
        message: 'Please specify an e-mail address',
      })
    })```

**Comment by acidjazz** [comment]
@productfrontenddeveloper you just need to use `this.$toast.show` and use `mounted()`
