### ISSUE TITLE
Tailwind classes not working in production

### ISSUE THREAD

**Issue by Dimi-Provatas** [acidjazz/tv-toast#30]
I have nuxt project that when built, the tailwind classes get purged. Am I missing something here?

I have added the node_modules line in the `tailwind.config.js`
`
... purge: { enabled: true, content: [... "node_modules/tv-*/dist/tv-*.umd.min.js",],}
`

I also added the configs in the `nuxt.config.js` file:
`
modules: [... [ "nuxt-tailvue", { all: true, toast: { defaultProps: { timeout: 5, progress: true, },},},],]`

In the first image you can see the development environment css in dev-tools, and on the second you can see the built version (clearly missing a lot of classes,  e.g. the z-40 and the inset-0):

![Screenshot 2022-04-29 at 15 35 41](https://user-images.githubusercontent.com/53426786/165945660-17eee53e-85cc-4a81-9fe4-ef9eacaf41fc.png)

![Screenshot 2022-04-29 at 15 38 41](https://user-images.githubusercontent.com/53426786/165945851-eecef5f0-b5ae-43a1-96a4-858542ba7e0b.png)

**Comment by alihajiloo** [comment]
I have this problem, too.

**Comment by acidjazz** [comment]
This has been sunset - please move to https://github.com/fumeapp/tailvue
