### ISSUE TITLE
Instructions for adding to purge to update

### ISSUE THREAD

**Issue by borisdayma** [acidjazz/tv-toast#5]
Hi,

I think this module is really great!
You forgot the `purge` parameter in the instructions: see [documentation](https://tailwindcss.com/docs/controlling-file-size#enabling-manually).

This solved my issue.

**Comment by acidjazz** [comment]
What exactly was your issue here?

**Comment by borisdayma** [comment]
I proposed #7 to fix this issue.

**Comment by acidjazz** [comment]
Thanks fixed!
