### ISSUE TITLE
Add more customization options

### ISSUE THREAD

**Issue by borisdayma** [acidjazz/tv-toast#6]
It would be great to customize a few more elements:
* icon
* display of progress bar (I currently set a timeout to 5 and same color as my background so it does not appear)
* position of notification, though this one is difficult as it would probably need to be reactive

**Comment by acidjazz** [comment]
for position of notification check how you can append classes to the containerClasses @borisdayma 

https://github.com/acidjazz/tv-toast#defaults

**Comment by acidjazz** [comment]
@borisdayma please create a separate issue for the icon, this is a difficult one to achieve since its prorgammatic

**Comment by borisdayma** [comment]
Thanks, I'll create a separate one for the icon.

Is the intent for the custom container classes to be added to the default ones or to be merged to them?

**Comment by acidjazz** [comment]
@borisdayma Yes, they just stack on to the default
