### ISSUE TITLE
Default prop class and setting

### ISSUE THREAD

**Issue by kokoraka** [acidjazz/tv-toast#9]
I wonder if we can set default prop and setting for the toast like, probably like this (att):
![a](https://user-images.githubusercontent.com/60498861/98447799-44348d00-215a-11eb-85f1-7eafdb0293c0.png)
![b](https://user-images.githubusercontent.com/60498861/98447801-4565ba00-215a-11eb-9e34-e6329c86244a.png)

Thanks

**Comment by acidjazz** [comment]
@kokoraka excellent idea, I'll try to get this in as soon as I get some time, PR's are also greatly appreciated!

**Comment by acidjazz** [comment]
Thanks to @mfollert this is now in v1.2.18, example [here](https://github.com/acidjazz/tv-toast#defaults-for-props)
